version: '3.3'
volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:12.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    image: dmitriyperetoka/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/var/www/foodgram/static
      - media_data:/var/www/foodgram/media
    env_file:
      - ./.env

  nginx:
    image: nginx:1.18
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_data:/var/www/foodgram/static:ro
      - media_data:/var/www/foodgram/media:ro
