# Generated by Django 3.1.6 on 2021-02-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Автор списка покупок', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
        migrations.CreateModel(
            name='RecipeInPurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Количество порций рецепта в списке покупок', verbose_name='Количество')),
                ('purchase_list', models.ForeignKey(help_text='Список покупок, в котором представлен рецепт', on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaselist', verbose_name='Список покупок')),
                ('recipe', models.ForeignKey(help_text='Рецепт, представленный в списке покупок', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепт в списке покупок',
                'verbose_name_plural': 'Рецепты в списках покупок',
            },
        ),
        migrations.AddField(
            model_name='purchaselist',
            name='recipes',
            field=models.ManyToManyField(help_text='Рецепты, представленные в списке покупок', related_name='purchase_lists', through='purchases.RecipeInPurchaseList', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AddConstraint(
            model_name='recipeinpurchaselist',
            constraint=models.UniqueConstraint(fields=('purchase_list', 'recipe'), name='unique_purchase_list_recipe'),
        ),
    ]
