# Generated by Django 3.1.6 on 2021-02-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='title',
            field=models.CharField(default='No title', help_text='Название списка покупок', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
