# Generated by Django 3.1.6 on 2021-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20210225_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinnewpurchaselist',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество порций рецепта в новом списке покупок', verbose_name='Количество'),
        ),
    ]
