# Generated by Django 3.1.6 on 2021-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_favouriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах', verbose_name='Время приготовления'),
        ),
    ]
