# Generated by Django 3.1.6 on 2021-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210316_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='dimension_unit',
            new_name='dimension',
        ),
    ]
