# Generated by Django 3.1.6 on 2021-03-21 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210319_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиента в рецепте', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
    ]
