# Generated by Django 3.1.6 on 2021-03-07 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_favouriterecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210223_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Рецепт, который пользователь добавил в список избранного', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Пользователь, который добавил рецепт в список избранного', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рецепт в списке избранного',
                'verbose_name_plural': 'Рецепты в списках избранного',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(help_text='Пользователь, который подписан на автора публикаций', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_authors', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.DeleteModel(
            name='FavouriteRecipe',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_recipe'),
        ),
    ]
