# Generated by Django 3.1.6 on 2021-03-14 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20210313_1259'),
        ('users', '0006_auto_20210313_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='RecipeInPurchaseList',
            new_name='Purchase',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite_recipe',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite'),
        ),
    ]
