# Generated by Django 3.1.6 on 2021-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210315_2219'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_recipe_in_purchase_list',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_purchase'),
        ),
    ]
