# Generated by Django 3.1.6 on 2021-03-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210316_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-recipe__pub_date'], 'verbose_name': 'Рецепт в списке избранного', 'verbose_name_plural': 'Рецепты в списках избранного'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-recipe__pub_date'], 'verbose_name': 'Рецепт в списке покупок', 'verbose_name_plural': 'Рецепты в списках покупок'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['author__first_name', 'author__last_name'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
